export const GET_DAILY_HISTORY = Symbol('HODL/GET_DAILY_HISTORY').toString()
export const GET_PRICE_PAIR = Symbol('HODL/GET_PRICE_PAIR').toString()
export const START_PRICE_TICKER = Symbol('HODL/START_PRICE_TICKER').toString()
export const TICKER_TIMER_REF = Symbol('HODL/TICKER_TIMER_REF').toString()
export const START_DATA_SUBSCRIPTION = Symbol('HODL/START_DATA_SUBSCRIPTION').toString()
export const STOP_DATA_SUBSCRIPTION = Symbol('HODL/STOP_DATA_SUBSCRIPTION').toString()
